### ISSUE TITLE
Flic making my app crash

### ISSUE THREAD

**Issue by JaimeFerBec** [50ButtonsEach/fliclib-android#10]
Before today my mobile application (which makes use of Flic) worked just fine, but since today's two Flic App's updates (via Google Play Store) my app crashes when trying to use Flic. More precisely, it crashes when calling `FlicManager.setAppCredentials(appId, appSecret, appName);`.
After some testing it seems that the call works only if I launch Flic App before launching my app. If at any point I kill the Flic App my app stops working too if it tries to make use of Flic. This did not happen before today's updates for the Flic App. Even if I did not start the Flic App at all my app was able to use fliclib without any restrictions, and obviously without crashing.

**Comment by Emill** [comment]
Sorry for this. We are actually going through this bug right now. We
identified the problem and are currently fixing it. We'll have to do yet
another release...

**Comment by Emill** [comment]
Can you recheck where you get the crash?
I can't believe it crashes in setAppCredentials, because as you see in https://github.com/50ButtonsEach/fliclib-android/blob/master/fliclib/src/main/java/io/flic/lib/FlicManager.java#L83 is does nothing except some assignments of variables.

**Comment by JaimeFerBec** [comment]
Yes, I also saw it in your code and couldn't believe it was there, but when I was debugging the app would crash before returning from that function.
Just in case it helps, the next call to your library that my code makes, and may be making the app crash is: `FlicManager.getInstance(Context context, FlicManagerInitializedCallback initializedCallback)`.

**Comment by Emill** [comment]
Just published a new app version. Try it once it becomes available on Play Store.

**Comment by JaimeFerBec** [comment]
I just updated Flic App and everything seems to be working just fine again.
Thanks for the quick fix.
