### ISSUE TITLE
Once out of range does not connect back again

### ISSUE THREAD

**Issue by safebomb** [50ButtonsEach/fliclib-android#13]
Hi Guys, 

Tested the newly sent out flic button with the Flic app. Clicks got recognized and all was well. 
Once i went out of range with the button, the Flic app failed to recognize any clicks. Even when i came back within range, the Flic App continued to show that the button is out of range. 
I had to literally close the app and do other things to get it to identify the button in range. 
Any idea how we can automate this as soon as the button comes within range?

**Comment by Emill** [comment]
This is a repository for Android SDK, not an issue tracker for the Flic app.

The button will automatically reconnect when you press it, if it is in range and the Bluetooth on your device is turned on. If you have further problems, contact support@shortcutlabs.com
