### ISSUE TITLE
Is Flic app required to use SDK?

### ISSUE THREAD

**Issue by AdamJakiela** [50ButtonsEach/fliclib-android#18]
I started reading the Android tutorial for integrating the Flic SDK and noticed the first step is to install the Flic app. Does this mean that users of my app will need to install the Flic app in order to use the Flic button within my application?

**Comment by fabianbergmark** [comment]
Yes

We have white label solutions too for companies where the Flic app is not required. This requires an order of at least 500 buttons.

**Comment by AdamJakiela** [comment]
Thanks @fabianbergmark
