### ISSUE TITLE
Upgrade gradle versions.

### ISSUE THREAD

**Issue by DevNigam** [50ButtonsEach/fliclib-android#22]
Hello Flic Team,

Thanks for a nice device and the library. But, please update the lib compile, target SDK version, gradle version. We are facing issue while importing the library into our Android Studio is of version 3.0 and facing issues. I updated the gradle for now to something like this

`compileSdkVersion 25`
`buildToolsVersion "26.0.2"`
`targetSdkVersion 25`
`compile 'com.android.support:appcompat-v7:25.4.0'`

**Comment by fabianbergmark** [comment]
Thanks for the suggestion, we will include it in the next release
