### ISSUE TITLE
Proofs are not equal

### ISSUE THREAD

**Issue by Josh8509** [50ButtonsEach/fliclib-android#27]
Hi guys
I have downloaded the flic app, and also integrated the flic module on Android studio, but the application is not grabbing a button.
I have checked the FlicManager.java Class and the issue is that the proofExpected and the proof are not equal. I wonder if you could help me on it, so I can continue with my proyect.
Regards

**Comment by Emill** [comment]
Hi. Does it help if you remove the battery from the button and insert it again?

Anyway, you should consider integrate our new Flic 2 buttons instead.

**Comment by Josh8509** [comment]
Great!!! it worked by removing the battery
We are about to buy some Flic2 buttons, one question, Is it also needed to have the Flic app installed for the sdk to work on the Flic 2? cuz I have read the documentation for Flic2 and it doesn't mention anything about it

**Comment by Emill** [comment]
With Flic 2 you don't need the Flic app installed.

**Comment by Josh8509** [comment]
Good, thanks for your help!!!
