### ISSUE TITLE
FlicAppNotInstalledException but it's installed.

### ISSUE THREAD

**Issue by RaviKoradiya** [50ButtonsEach/fliclib-android#28]
I am developing an app for my client, 
Implemented library and followed all steps given in the document.
still throwing `FlicAppNotInstalledException` even though the flic app is already installed and added a couple of flics as well into the app,

Please guide me.

the app is built for version android 30 so target and min SDK both versions are 30.
Testing on API level 30 (Android 11).

**Comment by Emill** [comment]
Does Logcat print anything useful? This happens when the https://developer.android.com/reference/android/content/Context#bindService(android.content.Intent,%20android.content.ServiceConnection,%20int) call returns false.

Anyway, if you want to program for Flic 2 buttons rather than Flic 1, you should use https://github.com/50ButtonsEach/flic2lib-android instead.

**Comment by RaviKoradiya** [comment]
I required both flic and flic2 support.
so implemented both libraries.

`registerReceiver(FlicButtonBroadcastReceiver(), IntentFilter("io.flic.FLICLIB_EVENT"))`
Is it ok if register broadcast like this?

and also have a query,
what will be `appId` in `FlicManager.setAppCredentials(` ?

**Comment by Emill** [comment]
Please see https://github.com/50ButtonsEach/fliclib-android#integrate-flic under `1.` for your second question and `4` for your first question. You should register the receiver in the manifest if you want the Flic app to wake up (i.e. start) your app when the button is pressed, in case the system killed your app due to inactivity.

**Comment by RaviKoradiya** [comment]
I have followed those steps, but for `1.` It says that appId will be generated from the developer portal, but can't find it there.
![image](https://user-images.githubusercontent.com/12453916/115675315-1cce2700-a36c-11eb-932f-f2db6e59eddc.png)

and I have added a receiver in the manifest, but still getting `FlicAppNotInstalledException`. Please guide me.
Logcat seems ok, can't find any useful solution from it.

**Comment by Emill** [comment]
Just press the developer portal link and login. Then it will look like this:
![image](https://user-images.githubusercontent.com/1660778/115683689-fea9fc00-a356-11eb-9695-20bf731d8604.png)

Are you sure it's this Flic app you have installed, and not another app by mistake? https://play.google.com/store/apps/details?id=io.flic.app

You could also try this app https://play.google.com/store/apps/details?id=io.flic.apps.flappyflic to see if you get the same error message. It works on my phone at least.

Lastly you could also try another phone, if something is strange with the one you have.

**Comment by RaviKoradiya** [comment]
I found the issue with the latest android version.
as I mentioned that my app is targeting API level 30. Android introduced [Package visibility in Android 11](https://developer.android.com/about/versions/11/privacy/package-visibility).
and the flic app's visibility is not open. so any app targeting API level 30 and above will get `FlicAppNotInstalledException`.

as a quick fix currently I am decreasing the target API version to 29 for my app.
**but in the future, it will not work.**

Thanks for your time and quick support.

**Comment by RaviKoradiya** [comment]
Also please change appId to key in the document so that any developer does not get confused.

**Comment by Emill** [comment]
If you add

```xml
<queries>
    <package android:name="io.flic.app" />
</queries>
```

in your manifest and you target API 30, does it work then?

**Comment by RaviKoradiya** [comment]
Yes, that works, thanks.
