### ISSUE TITLE
Unable to grab second button

### ISSUE THREAD

**Issue by JaimeFerBec** [50ButtonsEach/fliclib-android#7]
I am able to succesfully grab one Flic button in my app, but if I try to grab another button, or grab that button again, the `onActivityResult` callback function is never called, even though the grab button intent gets closed and my app's activity goes back to foreground. If I kill my app and launch it again I am then able to grab the button again, but only once.
The only thing I have implemented significantly different from the sample app you propose in the android tutorial [https://flic.io/partners/developers/android-tutorial](https://flic.io/partners/developers/android-tutorial) is the FlicManager instance retrieval:
`FlicManager.getInstance(this, new FlicManagerInitializedCallback() { ... });`
You propose calling `FlicManager.getInstance` every time the `onActivityResult` callback is called, but since I need to grab more than one button in my app I thought I could store the FlicManager in a variable like this:

``` java
FlicManager.getInstance(this.cordova.getActivity(), new FlicManagerInitializedCallback() {
    @Override
      public void onInitialized(FlicManager manager) {
          Flic.this.flicManager = manager;
      }
});
```

This would allow me to do the following:

``` java
public void onActivityResult(final int requestCode, final int resultCode, final Intent data) {
     FlicButton button = this.flicManager.completeGrabButton(requestCode, resultCode, data);
     // Do whatever I need to with the button
}
```

And this way I wouldn't have to call `FlicManager.getInstance` every time I want to grab a button.
My guess is that that is the cause of the problem. If that were the case, would there be a way to not call FlicManager.getInstance as many times as I want to grab a button and still be able to successfully grab it?

**Comment by Emill** [comment]
Does it work if you do as it's done in the tutorial?

**Comment by JaimeFerBec** [comment]
I changed my code so that every time I need the flicManager I obtain it by using `FlicManager.getInstance`, but the problem persists.
I also found on your documentation that the `FlicManager` class is a singleton class, so my previous approach is fine, and the tests I carried out seem to indicate that as well.
I checked thoroughly, and the problem remains the same: `onActivityResult` never gets called after I call `FlicManager.initiateGrabButton` and grab a button on your GUI for the second straight time. Hence it looks like the issue is in the code of the android fliclib SDK.

**Comment by JaimeFerBec** [comment]
Another update: even if I don't grab any button the first time I call `FlicManager.initiateGrabButton` I'm not able to grab a button the second and subsequent times I call `FlicManager.initiateGrabButton`.
So the exact steps to reproduce the issue are the following:
1. Call `FlicManager.initiateGrabButton`.
2. Grab a button or simply go back to your app without grabbing any button.
3. Call `FlicManager.initiateGrabButton` again.
4. This time try to grab a button.
5. The Flic grab button GUI disappears and the app goes back to the previous activity, but `onActivityResult` never gets called.

**Comment by Emill** [comment]
I've tried to reproduce but it works for me. What phone / tablet model and Android OS are you using?

**Comment by JaimeFerBec** [comment]
I tested on a Google Nexus 4 phone, Android 5.1.1.
I tried the cordova plugin and sample app from here [https://github.com/jguix/Cordova-Flic](https://github.com/jguix/Cordova-Flic) and it works just fine grabbing a button several times in a row, so the issue doesn't seem to depend on the phone/OS.
It looks like it may have something to do with my own code (either the plugin or the app). I'll dig a little bit more into it and tell you what I find out.

**Comment by JaimeFerBec** [comment]
Ok, I finally solved it: I was calling `this.cordova.setActivityResultCallback(this);` only once, in my initialization function. But it is necessary to call it every time `flicManager.initiateGrabButton` is called in order for cordova to know which callback to call. This is what was preventing `onActivityResult` from being called on the second and subsequent grabbing button attempts.
This of course only applies if you are developing a cordova plugin to manage the communication with the flic button.

**Comment by Emill** [comment]
I see. You could post an issue in that github repo to point that out.

**Comment by santhosh-annam** [comment]
Is there a way to grab the buttons in our app without having flic app installed on android device?
